name: Release

on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

  release:
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        run: |
          echo ${{ secrets.YANDEX_OAUTH_TOKEN }} | docker login cr.yandex -u oauth --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }} .
          docker tag cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }} cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}_latest

      - name: Push Docker image to registry
        run: |
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.YANDEX_REGISTRY_ID }}/app:${{ github.run_number }}_latest

      - name: Create release branch
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout -b releases/${{ github.run_number }}
          git push origin releases/${{ github.run_number }}

      - name: Create release tag
        run: |
          git tag -a v${{ github.run_number }} -m "Release ${{ github.run_number }}"
          git push origin v${{ github.run_number }}

      - name: Update CHANGELOG.md
        id: update_changelog
        run: |
          echo "## Release ${{ github.run_number }}" > temp_changelog.md
          echo "$(cat temp_changelog.md CHANGELOG.md)" > CHANGELOG.md
          git commit -am "Update CHANGELOG.md"
          git push origin main
          
      - name: Create issue content
        id: create_content
        run: |
          echo "## Release ${{ github.run_number }}" > release_info.md
          echo "- **Date:** $(date)" >> release_info.md
          echo "- **Author:** ${{ github.actor }}" >> release_info.md
          echo "- **Version:** ${{ github.run_number }}" >> release_info.md
          echo "- **Commits:** ${{ steps.changelog.outputs.commits }}" >> release_info.md
          echo "- **Docker Image:** cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}" >> release_info.md

      - name: Create Github Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Release ${{ github.run_number }}
          content-filepath: release_info.md
